
spring:
  profiles:
    active: test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xiaohe66_web_test?characterEncoding=UTF-8&amp;useUnicode=true&amp;autoReconnect=true
    username: root
    password: root

server:
  port: 8081

logging:
  file:
    path: /home/xiaohe/test/log/

xiaohe66:
  file:
    home: /home/xiaohe/test/file/
    maxMbChunkPer: 2
    maxMbFilePer: 64
  registerUrl: https://test.xiaohe66.com/sec/login/register/