#--------------------------------------------
spring:
  resources:
    # 配置静态资源路径，默认配置失效[public、static、META-INF/resource]
    static-locations: ["classpath:/static"]
  mvc:
    static-path-pattern: /**
  thymeleaf:
    prefix: classpath:/template
  datasource:
    hikari:
      # 最小空闲时连接数
      minimum-idle: 2
#-------------------------------------------
server:
  tomcat:
    # 配置Tomcat编码,默认为UTF-8
    uri-encoding: UTF-8
#------------- mybatis ---------------------------------
mybatis-plus:
  # 配置MyBaties全局配置文件:mybatis-config.xml
  config-location: classpath:/mybatis-config.xml
  # 对应实体类的包名
  type-aliases-package: com.xiaohe66.web.code
  # 和 typeAliasesPackage 配合使用，表示仅描述该类的子类
  type-aliases-super-type: com.xiaohe66.web.base.base.BasePo
  # mapper.xml文件所在位置
  mapper-locations: classpath:/mapper/**/*.xml

#------------- logback ---------------------------------
logging:
  config: classpath:logback-spring.xml
  pattern:
    console: '%d{HH:mm:ss.SSS} %highlight[%-5p] [%thread] %cyan(%logger{15}) >>> %msg %n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5p] [%thread] %logger{30} >>> %msg %n'

#------------- shrio ---------------------------------
#配置性参数
xiaohe66:
  wx:
    miniProgramState: developer
    appId: appid
    appSecret: secret