spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/xiaohe66_web?characterEncoding=UTF-8&amp;useUnicode=true&amp;autoReconnect=true
    username: xiaohe66_web
    password: xiaohe66_web

server:
  port: 8080

logging:
  file:
    path: /home/xiaohe/logs/

xiaohe66:
  file:
    home: /home/xiaohe/file/
    maxMbChunkPer: 2
    maxMbFilePer: 64
  registerUrl: https://xiaohe66.com/sec/login/register/
